/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 chart_bio.gltf --transform
Author: Shalmon (https://sketchfab.com/nashalanandas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chart-for-bioprospecting-8c4013ca6f944475a009973a94510301
Title: Chart for Bioprospecting
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/chart_bio-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[1.43, 0, 4.44]} rotation={[-Math.PI, 0.53, -Math.PI]} scale={[1.29, 0.12, 1.29]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-0.52, 0, 3.3]} rotation={[-Math.PI, 0.53, -Math.PI]} scale={[1.29, 0.12, 1.29]}>
        <mesh geometry={nodes.Object_7.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-1.07, 0.28, 1.22]} rotation={[0, 0.37, -Math.PI / 2]} scale={0.17}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.vidro} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.salat} position={[0, 2.12, 0]} scale={1.01} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.salat} position={[0.1, 4.14, -1.05]} rotation={[-0.74, 0, -0.03]} scale={1.03} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.salat} position={[0.12, 4.64, -0.4]} rotation={[-0.74, 0, -0.03]} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.salat} position={[0.91, 6.17, 0.69]} rotation={[2.99, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.salat} position={[0.82, 1.77, 0.01]} rotation={[-0.56, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.salat} position={[0.75, 1.65, 0.26]} rotation={[-2.65, -0.2, 1.46]} scale={0.19} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.salat} position={[0.63, 2.45, -0.05]} rotation={[-2.1, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.salat} position={[0.92, 4.23, -0.41]} rotation={[0, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.salat} position={[0.91, 6.29, 0.29]} rotation={[-0.96, 0, -Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.salat} position={[0.92, 4.61, -0.27]} rotation={[-0.86, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.salat} position={[0.92, 3.07, 0.1]} rotation={[-1.58, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.salat} position={[0.92, 3.45, 0.27]} rotation={[-0.23, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.salat} position={[0.92, 4.04, -0.07]} rotation={[-1.86, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.salat} position={[0.87, 4.42, -0.11]} rotation={[-1.62, -0.29, 1.73]} scale={0.19} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.salat} position={[0.92, 4.76, 0.1]} rotation={[-2.8, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.salat} position={[0.92, 3.86, 0.33]} rotation={[-0.69, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.salat} position={[0.82, 1.35, 0.01]} rotation={[-0.56, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.salat} position={[0.76, 1.54, -0.17]} rotation={[2.68, 0.14, 1.56]} scale={0.19} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.salat} position={[0.91, 5.02, -0.21]} rotation={[2.2, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.salat} position={[0.91, 4.41, 0.28]} rotation={[1.75, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.salat} position={[0.83, 4.21, 0.3]} rotation={[1.88, 0.63, -2.18]} scale={0.19} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.salat} position={[0.92, 4.31, 0.66]} rotation={[-2.71, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.salat} position={[0.54, 2.43, 0.14]} rotation={[-2.74, -0.01, 1.84]} scale={0.19} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.salat} position={[0.92, 4.74, 0.49]} rotation={[-1.87, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.salat} position={[0.91, 5.08, 0.32]} rotation={[-2.49, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.salat} position={[0.91, 3.92, 0.72]} rotation={[2, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.salat} position={[0.92, 5.61, -0.33]} rotation={[3.02, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.salat} position={[0.91, 5.44, -0.71]} rotation={[1.93, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.salat} position={[0.91, 6.17, -0.59]} rotation={[0.56, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.salat} position={[0.92, 5.88, -0.87]} rotation={[-1.88, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.salat} position={[0.92, 6.45, -0.21]} rotation={[-2.91, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.salat} position={[0.91, 5.62, 0.11]} rotation={[-0.33, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.salat} position={[0.91, 6.67, 0.4]} rotation={[1.55, 0, -Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.salat} position={[0.92, 5.46, 0.82]} rotation={[-2.49, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.salat} position={[0.84, 5.91, -0.56]} rotation={[-2.97, -0.33, 1.22]} scale={0.19} />
        <mesh geometry={nodes.Object_82.geometry} material={materials.salat} position={[0.91, 6.96, -0.35]} rotation={[2.2, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_84.geometry} material={materials.salat} position={[0.92, 6.99, -0.92]} rotation={[-2.8, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_86.geometry} material={materials.salat} position={[0.92, 6.34, -0.94]} rotation={[-1.86, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_88.geometry} material={materials.salat} position={[0.91, 4.91, -1.21]} rotation={[2.12, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_90.geometry} material={materials.salat} position={[0.92, 6.53, -1.28]} rotation={[0, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_92.geometry} material={materials.salat} position={[0.92, 5.7, -1.52]} rotation={[-0.68, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_94.geometry} material={materials.salat} position={[0.91, 5.99, -1.79]} rotation={[1.26, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_96.geometry} material={materials.salat} position={[0.92, 7.06, -1.55]} rotation={[1.5, 0, Math.PI / 2]} scale={0.19} />
        <mesh geometry={nodes.Object_98.geometry} material={materials.salat} position={[0.49, 2.36, -0.32]} rotation={[-2.35, -0.35, 1.87]} scale={0.19} />
        <mesh geometry={nodes.Object_100.geometry} material={materials.salat} position={[0.49, 1.76, -0.61]} rotation={[-2.35, -0.35, 1.87]} scale={0.19} />
        <mesh geometry={nodes.Object_102.geometry} material={materials.salat} position={[0.58, 1.89, -0.19]} rotation={[-2.74, -0.01, 1.84]} scale={0.19} />
        <mesh geometry={nodes.Object_104.geometry} material={materials.salat} position={[0.66, 1.84, -0.35]} rotation={[-2.1, 0, 1.7]} scale={0.19} />
        <mesh geometry={nodes.Object_106.geometry} material={materials.vidro} position={[0, 2.52, 0]} rotation={[Math.PI / 2, 0, 1.7]} scale={0.39} />
        <mesh geometry={nodes.Object_108.geometry} material={materials.salat} position={[0, 0, 0.02]} />
      </group>
      <group position={[1.91, 0.11, 4.53]} rotation={[Math.PI / 2, 0, 0.65]} scale={0.03}>
        <mesh geometry={nodes.Object_110.geometry} material={materials.st_tile} />
        <mesh geometry={nodes.Object_111.geometry} material={materials.material} />
      </group>
      <group position={[1.01, 0.13, 4.36]} rotation={[Math.PI / 2, 0, 2]} scale={0.05}>
        <mesh geometry={nodes.Object_113.geometry} material={materials.Material_414} />
        <mesh geometry={nodes.Object_114.geometry} material={materials.Material_416} />
        <mesh geometry={nodes.Object_115.geometry} material={materials.Black} />
      </group>
      <group position={[-0.42, 0.14, 3.19]} rotation={[1.34, 0.24, -2.35]} scale={0.13}>
        <mesh geometry={nodes.Object_117.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_118.geometry} material={materials.blinn5} />
        <mesh geometry={nodes.Object_119.geometry} material={materials.Iron} />
        <mesh geometry={nodes.Object_120.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_121.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Object_122.geometry} material={materials.Blush} />
        <mesh geometry={nodes.Object_123.geometry} material={materials.Crystal} />
      </group>
      <group position={[3.96, 0.37, 3.44]} rotation={[-Math.PI, -0.89, -Math.PI]} scale={0.5}>
        <mesh geometry={nodes.Object_125.geometry} material={materials.salat_0} />
        <mesh geometry={nodes.Object_127.geometry} material={materials.salat} />
        <mesh geometry={nodes.Object_129.geometry} material={materials.salat_1} />
        <mesh geometry={nodes.Object_131.geometry} material={materials.mayonez} position={[1.5, -0.14, 1.43]} />
        <mesh geometry={nodes.Object_133.geometry} material={materials.salat_2} position={[1.33, -0.17, 1.3]} />
        <mesh geometry={nodes.Object_135.geometry} material={materials.salat_2} position={[1.22, -0.08, 1.37]} />
        <mesh geometry={nodes.Object_137.geometry} material={materials.salat_2} position={[1.33, -0.12, 1.07]} />
        <mesh geometry={nodes.Object_139.geometry} material={materials.salat_2} position={[1.31, -0.13, 1.05]} />
        <mesh geometry={nodes.Object_141.geometry} material={materials.salat_2} position={[1.33, -0.27, 1.45]} />
        <mesh geometry={nodes.Object_143.geometry} material={materials.ketchup} position={[1.09, -0.05, 1.18]} />
        <mesh geometry={nodes.Object_145.geometry} material={materials.salat_2} position={[1.15, -0.05, 1.37]} />
        <mesh geometry={nodes.Object_147.geometry} material={materials.salat_2} position={[1.36, -0.19, 1.49]} />
        <mesh geometry={nodes.Object_149.geometry} material={materials.salat_2} position={[1.26, -0.27, 0.97]} />
        <mesh geometry={nodes.Object_151.geometry} material={materials.salat_2} position={[1.21, -0.13, 0.94]} />
        <mesh geometry={nodes.Object_153.geometry} material={materials.salat_2} position={[1.44, -0.26, 1.36]} />
        <mesh geometry={nodes.Object_155.geometry} material={materials.salat_2} position={[1.31, -0.28, 1.02]} />
        <mesh geometry={nodes.Object_157.geometry} material={materials.salat_2} position={[1.08, -0.07, 1.16]} />
        <mesh geometry={nodes.Object_159.geometry} material={materials.salat_2} position={[1.33, -0.08, 1.47]} />
        <mesh geometry={nodes.Object_161.geometry} material={materials.salat_2} position={[1.27, -0.09, 1.11]} />
        <mesh geometry={nodes.Object_163.geometry} material={materials.salat_2} position={[1.34, -0.29, 1.15]} />
        <mesh geometry={nodes.Object_165.geometry} material={materials.salat_2} position={[1.34, -0.2, 1.48]} />
        <mesh geometry={nodes.Object_167.geometry} material={materials.salat_2} position={[1.27, -0.09, 1.11]} />
        <mesh geometry={nodes.Object_169.geometry} material={materials.salat_2} position={[1.22, -0.11, 1.17]} />
        <mesh geometry={nodes.Object_171.geometry} material={materials.salat_2} position={[1.53, -0.28, 1.41]} />
        <mesh geometry={nodes.Object_173.geometry} material={materials.salat_2} position={[1.37, -0.15, 1.17]} />
        <mesh geometry={nodes.Object_175.geometry} material={materials.salat_2} position={[1.24, -0.01, 1.15]} />
        <mesh geometry={nodes.Object_177.geometry} material={materials.salat_2} position={[1.45, -0.29, 1.15]} />
        <mesh geometry={nodes.Object_179.geometry} material={materials.salat_2} position={[1.5, -0.06, 1.22]} />
        <mesh geometry={nodes.Object_181.geometry} material={materials.salat_2} position={[1.38, -0.08, 1.13]} />
        <mesh geometry={nodes.Object_183.geometry} material={materials.salat_2} position={[1.02, -0.24, 1.19]} />
        <mesh geometry={nodes.Object_185.geometry} material={materials.salat_2} position={[1.25, -0.27, 1.31]} />
        <mesh geometry={nodes.Object_187.geometry} material={materials.salat_3} position={[0.73, -0.15, 1.22]} />
        <mesh geometry={nodes.Object_189.geometry} material={materials.salat_4} position={[0.39, -0.39, 1.32]} />
        <mesh geometry={nodes.Object_191.geometry} material={materials.salat_2} position={[1.42, -0.28, 1.42]} />
        <mesh geometry={nodes.Object_193.geometry} material={materials.salat_2} position={[1.33, -0.16, 1]} />
      </group>
      <group position={[2.69, 0.3, 1.22]} rotation={[-Math.PI / 2, 0, -0.59]} scale={0.85}>
        <mesh geometry={nodes.Object_195.geometry} material={materials.App781} />
        <mesh geometry={nodes.Object_196.geometry} material={materials.App781} />
        <mesh geometry={nodes.Object_197.geometry} material={materials.App781} />
        <mesh geometry={nodes.Object_198.geometry} material={materials.App741} />
        <mesh geometry={nodes.Object_199.geometry} material={materials.App741} />
        <mesh geometry={nodes.Object_200.geometry} material={materials.App741} />
        <mesh geometry={nodes.Object_201.geometry} material={materials.App741} />
        <mesh geometry={nodes.Object_202.geometry} material={materials.AppDC} />
        <mesh geometry={nodes.Object_203.geometry} material={materials.AppDC} />
        <mesh geometry={nodes.Object_204.geometry} material={materials.AppDC} />
        <mesh geometry={nodes.Object_205.geometry} material={materials.AppDC} />
        <mesh geometry={nodes.Object_206.geometry} material={materials.AppDC} />
        <mesh geometry={nodes.Object_207.geometry} material={materials.AppDC} />
        <mesh geometry={nodes.Object_208.geometry} material={materials.AppDC} />
        <mesh geometry={nodes.Object_209.geometry} material={materials.App443} />
        <mesh geometry={nodes.Object_210.geometry} material={materials.App443} />
        <mesh geometry={nodes.Object_211.geometry} material={materials.App443} />
        <mesh geometry={nodes.Object_212.geometry} material={materials.App443} />
        <mesh geometry={nodes.Object_213.geometry} material={materials.App443} />
        <mesh geometry={nodes.Object_214.geometry} material={materials.App443} />
        <mesh geometry={nodes.Object_215.geometry} material={materials.App7B} />
      </group>
      <group position={[3.78, 0.32, 0.64]} rotation={[0.18, 0.79, -0.13]} scale={0.65}>
        <mesh geometry={nodes.Object_217.geometry} material={materials.salat_5} />
        <mesh geometry={nodes.Object_218.geometry} material={materials.salat_5} />
      </group>
      <group position={[1.46, 0, 2.16]} rotation={[-Math.PI, 0.53, -Math.PI]} scale={[1.29, 0.12, 1.29]}>
        <mesh geometry={nodes.Object_240.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_241.geometry} material={materials['Material.002']} />
      </group>
      <group position={[3.42, 0, 3.3]} rotation={[-Math.PI, 0.53, -Math.PI]} scale={[1.29, 0.12, 1.29]}>
        <mesh geometry={nodes.Object_243.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_244.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-0.52, 0, 1.03]} rotation={[-Math.PI, 0.53, -Math.PI]} scale={[1.29, 0.12, 1.29]}>
        <mesh geometry={nodes.Object_246.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_247.geometry} material={materials['Material.002']} />
      </group>
      <group position={[3.44, 0, 1.04]} rotation={[-Math.PI, 0.53, -Math.PI]} scale={[1.29, 0.12, 1.29]}>
        <mesh geometry={nodes.Object_249.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_250.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes.Object_220.geometry} material={materials['Material.007']} position={[3.21, 0.49, 1.29]} rotation={[-3.14, 0.94, 3.08]} scale={[0.01, 0, 0]} />
      <mesh geometry={nodes.Object_222.geometry} material={materials['Material.003']} position={[3.49, 0.49, 1.16]} rotation={[0, -0.86, 0]} scale={0.12} />
      <mesh geometry={nodes.Object_224.geometry} material={materials['Material.010']} position={[3.49, 0.49, 1.16]} rotation={[0, -0.86, 0]} scale={0.11} />
      <mesh geometry={nodes.Object_226.geometry} material={materials['Material.009']} position={[3.48, 0.51, 1.16]} rotation={[0, -0.86, 0]} scale={0.03} />
      <mesh geometry={nodes.Object_228.geometry} material={materials['Material.004']} position={[3.5, 0.47, 1.24]} rotation={[0, -0.86, 0]} scale={[0.12, 0.13, 0.13]} />
      <mesh geometry={nodes.Object_230.geometry} material={materials['Material.007']} position={[3.37, 0.45, 1.48]} rotation={[0, -0.1, 0]} scale={0.04} />
      <mesh geometry={nodes.Object_232.geometry} material={materials['Material.005']} position={[3.49, 0.49, 1.16]} rotation={[0, -0.86, 0]} scale={0.12} />
      <mesh geometry={nodes.Object_234.geometry} material={materials['Material.008']} position={[3.49, 0.49, 1.16]} rotation={[0, -0.86, 0]} scale={0.12} />
      <mesh geometry={nodes.Object_236.geometry} material={materials['Material.012']} position={[3.17, 0.49, 1.43]} rotation={[-3.14, 0.94, 3.08]} scale={[0.01, 0, 0]} />
      <mesh geometry={nodes.Object_238.geometry} material={materials['Material.013']} position={[3.5, 0.49, 1.23]} rotation={[0, -0.86, 0]} scale={[0.13, 0.14, 0.14]} />
      <mesh geometry={nodes.Object_252.geometry} material={materials['Material.002']} position={[1.44, 0.14, 1.76]} scale={0.34} />
      <mesh geometry={nodes.Object_254.geometry} material={materials['Material.002']} position={[-0.5, 0.14, 1.94]} scale={0.34} />
      <mesh geometry={nodes.Object_256.geometry} material={materials['Material.002']} position={[-0.53, 0.14, 4.2]} scale={0.3} />
      <mesh geometry={nodes.Object_258.geometry} material={materials['Material.002']} position={[1.42, 0.14, 5.38]} scale={0.3} />
      <mesh geometry={nodes.Object_260.geometry} material={materials['Material.002']} position={[3.43, 0.14, 4.06]} scale={0.24} />
      <mesh geometry={nodes.Object_262.geometry} material={materials['Material.002']} position={[3.45, 0.14, 1.8]} scale={0.2} />
    </group>
  )
}

useGLTF.preload('/chart_bio-transformed.glb')
