/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 game_design.gltf --transform
Author: bocharova (https://sketchfab.com/apsnu)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/crypt-location-ea79b3b36fc04ded845ddfe1de08957a
Title: Crypt Location
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/game_design-transformed.glb')
  return (
    <group {...props} dispose={null} scale={[2, 2, 2]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.map_3_castle} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.map_3_objects1} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.map_3_terrain1} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.initialShadingGroup} />
      </group>
    </group>
  )
}

useGLTF.preload('/game_design-transformed.glb')
